#!/usr/bin/env python3
"""
Render five v0.3 (prompt v6) prompts to docs/v0.3-sample-prompts.md for reading.

No model is called. We pick one case per answer-key group, each with a fixed rule
over the sample file order, so re-running the script picks the same cases:

1. main sample, R10 target from the true condition (first MI case);
2. main sample, R10 target from DXA only (first case whose truth is not tier 1 and has an R10 target);
3. main sample, clearly low-risk (first URTI case that is clearly low-risk);
4. atypical pool (first case: tier-1 truth, DXA's top diagnosis tier 3);
5. high-risk pool (first case: a non-truth tier-1 condition at DXA p >= 10%).

For each case we show the v6 user prompt and the v0.3 key fields the model never sees.
"""

from __future__ import annotations

import copy
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from evaluator import answer_key_v03 as ak  # noqa: E402
from inference.prompt import SYSTEM_PROMPT_V6  # noqa: E402
from inference.run_inference import build_messages_v6  # noqa: E402

TS = ROOT / "data" / "test_sets"
OUT = ROOT / "docs" / "v0.3-sample-prompts.md"

SETS = {
    "main": (TS / "eval-v02-adult.json", TS / "eval-v03-key.csv", TS / "eval-v03-key.sha256"),
    "atypical": (TS / "eval-v03-pool-atypical.json", TS / "eval-v03-pool-atypical.key.csv", TS / "eval-v03-pool-atypical.key.sha256"),
    "high-risk": (TS / "eval-v03-pool-high-risk.json", TS / "eval-v03-pool-high-risk.key.csv", TS / "eval-v03-pool-high-risk.key.sha256"),
}

PICKS = [
    ("Main sample: R10 target from the true condition", "main",
     lambda c, k: c["true_pathology"] == "Possible NSTEMI / STEMI"),
    ("Main sample: R10 target from DXA only", "main",
     lambda c, k: k.truth_tier != 1 and bool(k.r10)),
    ("Main sample: clearly low-risk", "main",
     lambda c, k: c["true_pathology"] == "URTI" and k.clearly_low_risk),
    ("Atypical pool: tier-1 truth, DXA's top diagnosis tier 3", "atypical", lambda c, k: True),
    ("High-risk pool: a non-truth tier-1 condition at DXA p >= 10%", "high-risk", lambda c, k: True),
]


def describe(k: ak.CaseKeyV03) -> str:
    group = "R10 target" if k.r10 else "clearly low-risk" if k.clearly_low_risk else "intermediate (either answer is free)"
    tg = "; ".join(f"{c} ({t.source}, DXA {t.dxa_p:.1f}%)" for c, t in k.considered.items() if t.in_r10) or "none"
    r5 = ", ".join(c for c, t in k.considered.items() if t.in_r5 and not t.in_r10) or "none"
    return (f"true condition {k.truth} (tier {k.truth_tier}); group: {group}; R10 targets: {tg}; "
            f"R5-only targets: {r5}; red flag: {', '.join(k.red_flag_names) or 'none'}")


def main() -> None:
    data = {}
    for name, (cases_path, key_path, sha_path) in SETS.items():
        data[name] = (json.loads(cases_path.read_text())["cases"], ak.load_key(key_path, sha_path))
    lines = [
        "# v0.3 sample prompts",
        "",
        "Generated by `scripts/render_v03_sample_prompts.py`. No model was called. The system prompt is the same for",
        "every case, so it appears once. For each case we show the prompt v6 user message and the v0.3 answer-key",
        "fields (spec/v0.3-scoring.md section 4), which the model never sees.",
        "",
        "## System prompt (v6)",
        "",
        "```",
        SYSTEM_PROMPT_V6,
        "```",
        "",
    ]
    for n, (title, name, rule) in enumerate(PICKS, 1):
        cases, key = data[name]
        case = next(c for c in cases if rule(c, key[c["case_id"]]))
        user = build_messages_v6(copy.deepcopy(case))[1]["content"]
        lines += [
            f"## {n}. {title} (`{case['case_id']}`)",
            "",
            f"Answer key, not shown to the model: {describe(key[case['case_id']])}.",
            "",
            "User prompt (v6):",
            "",
            "```",
            user,
            "```",
            "",
        ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
