#!/usr/bin/env python3
"""
Render five v0.2 (prompt v5) prompts to docs/v0.2-sample-prompts.md for reading.

No model is called. We pick five cases from data/test_sets/eval-v02-adult.json
that exercise the v0.2 input changes, each with a fixed rule, so re-running the
script picks the same cases:

1. the first cluster-headache case with the thunderclap red flag (onset scale value);
2. the first anemia case with a bleeding red flag;
3. the first female inguinal-hernia case (testicle site rendered as genital area);
4. the first pancreatic-neoplasm case (jaundice as a yellow skin lesion, listed defect);
5. the first PSVT case with no pain (default pain details dropped).

Each case also shows the v4 rendering of the same case, so the reader can see what changed.
"""

from __future__ import annotations

import copy
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from inference.prompt import SYSTEM_PROMPT_INTAKE_V5  # noqa: E402
from inference.run_inference import build_messages_v5, format_case_for_prompt  # noqa: E402

SAMPLE = ROOT / "data" / "test_sets" / "eval-v02-adult.json"
OUT = ROOT / "docs" / "v0.2-sample-prompts.md"

PICKS = [
    ("Cluster headache, thunderclap red flag", lambda c: c["true_pathology"] == "Cluster headache" and "thunderclap_headache" in c["offlist_red_flag_reasons"]),
    ("Anemia, bleeding red flag", lambda c: c["true_pathology"] == "Anemia" and "bleeding" in c["offlist_red_flag_reasons"]),
    ("Inguinal hernia, female patient", lambda c: c["true_pathology"] == "Inguinal hernia" and c["sex"] == "female"
     and any(e in c["presenting_symptoms"] for e in ("E_55_@_V_168", "E_55_@_V_169"))),
    ("Pancreatic neoplasm, jaundice as a skin lesion", lambda c: c["true_pathology"] == "Pancreatic neoplasm" and "E_130_@_V_107" in c["presenting_symptoms"]),
    ("PSVT without pain", lambda c: c["true_pathology"] == "PSVT" and "E_53" not in c["presenting_symptoms"]),
]


def main() -> None:
    cases = json.loads(SAMPLE.read_text())["cases"]
    lines = [
        "# v0.2 sample prompts",
        "",
        "Generated by `scripts/render_v02_sample_prompts.py` from `data/test_sets/eval-v02-adult.json`. No model was called.",
        "The system prompt is the same for every case, so it appears once. For each case we show the v5 user prompt,",
        "the answer-key fields the model never sees, and the v4 rendering of the same case for comparison.",
        "",
        "## System prompt (v5)",
        "",
        "```",
        SYSTEM_PROMPT_INTAKE_V5,
        "```",
        "",
    ]
    for n, (title, rule) in enumerate(PICKS, 1):
        case = next(c for c in cases if rule(c))
        v5_user = build_messages_v5(copy.deepcopy(case))[1]["content"]
        v4_user = format_case_for_prompt(copy.deepcopy(case), "intake")
        group = "serious" if case["serious"] else "at risk, not serious" if case["at_risk"] else "clearly low-risk"
        key = (f"true condition {case['true_pathology']}; DDXPlus severity {case['ddxplus_severity']}; "
               f"DXA P(serious risk) {case['p_serious_risk']:.1f}% ({group}); off-list red flag: "
               + (", ".join(case["offlist_red_flag_reasons"]) or "none"))
        lines += [
            f"## {n}. {title} (`{case['case_id']}`)",
            "",
            f"Answer key, not shown to the model: {key}.",
            "",
            "User prompt (v5):",
            "",
            "```",
            v5_user,
            "```",
            "",
            "<details><summary>Same case under v4</summary>",
            "",
            "```",
            v4_user,
            "```",
            "",
            "</details>",
            "",
        ]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
